// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlyaqgtvtdguwqitqnql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1seWFxZ3R2dGRndXdxaXRxbnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMjY0OTQsImV4cCI6MjA5MDcwMjQ5NH0.gVSl9gTcVYll2FhO-7DWE1cy2wYsU3sQdlTnHHhnQnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});